jobs:
  run-models:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Show environment
        run: |
          python --version
          pip list

      - name: Run DecisionTree (train.py)
        run: |
          python train.py

      - name: Run KernelRidge (train2.py)
        run: |
          python train2.py